version: '3.9'

networks:
  evam:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - evam

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: evam_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    #   MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "4306:3306"
    networks:
      - evam

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - evam

#   composer:
#     build:
#       context: .
#       dockerfile: ./docker/composer/DockerFile
#     container_name: composer
#     volumes:
#       - ./:/var/www/html
#     working_dir: /var/www/html
#     depends_on:
#       - php
#     user: laravel
#     entrypoint: ['composer', '--ignore-platform-reqs']
#     networks:
#       - evam

#   npm:
#     image: node:lts-alpine
#     container_name: npm
#     volumes:
#       - ./:/var/www/html
#     working_dir: /var/www/html
#     entrypoint: ['npm']
#     networks:
#       - evam
